### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by kalavhan**
pull request for milestone 2 review

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great start @team :clap: However, some requirements needs to be implemented in order to get approval for this milestone. check :arrow_down: 

##### Behaviour

* [ ] In this step not everything must work, you can incorporate the methods below as if they were imported from another concept like game, board, player,etc (you will work on that in subsequent milestone). You might even do it only with inline comments. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  * [ ] `[OPTIONAL]` game ask players for their names
  * [ ] `[REQUIRED]` game tells which player turn it is
  * [ ] `[REQUIRED]` game informs player if selected move is a winning move
  * [ ] `[REQUIRED]` game informs player if selected move is a draw move
  * [ ] `[REQUIRED]` game repeats all actions for next player's move.

##### Implementation details

* [ ] Inside loop, all actions should be repeated for each player **individually**
- Use switching turns to avoid redundant code.
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). Instead of a counter variable, you can use conditions as below:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by kalavhan** [comment]
Thank you @stratospherique for your feedback, however some of the issues you raised were already treated

[REQUIRED] game informs player if selected move is a winning move
   - Line 45 and 72 satisfies this requirement informing if there is a winner and stoping the game

[REQUIRED] game informs player if selected move is a draw move
  -Line 47 satisfies this requirement informing about a draw if all 9 positions have been selected and there has not been a winner

[REQUIRED] game repeats all actions for next player's move.
  -Line 25 asks player "X" for his move
  -Line 52 asks player "O" for his move

  -Line 30 validates the option selected by player "X"
  -Line 57 validates the option selected by player "O"

  -Line 35 prints the position taked by player "X"
  -Line 62 prints the position taked by player "O"

  -Line 45 informs if player "X" has won with the position taken
  -Line 72 informs if player "O" has won with the position taken

A loop needs to be terminated at some point (after a winning move or draw to be more specific). Instead of a counter variable, you can use conditions as below:
  -For the purpose of this milestone we decided to work with a variable called "board" which automatically increases after player makes a move, the while condition ensures that game continues until the board is filled up, also we have break points in case a player wins

**Review by uche-inyama — APPROVED** [review]
## Approved

Hi team, :wave: 

Everything is working fine, go ahead and merge with development.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by fegzycole** [comment]
Thank you for your prompt feedback @uche-inyama 

Have a great day!

**Pull request merged**
